/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Hp' at '6/11/20 2:30 PM' with Gradle 3.0
 *
 * @author Hp, @date 6/11/20 2:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
